export const ALERT_TYPES = {
  OVERSPEED: 'OVERSPEED',
  ENGINE_ON: 'ENGINE_ON',
  ENGINE_OFF: 'ENGINE_OFF',
  GEOFENCE_ENTER: 'GEOFENCE_ENTER',
  GEOFENCE_EXIT: 'GEOFENCE_EXIT',
  BATTERY_DISCONNECTED: 'BATTERY_DISCONNECTED',
  DEVICE_EXPIRY: 'DEVICE_EXPIRY',
  CALL_REQUIRED: 'CALL_REQUIRED',  // ✅ added
};

export const ALERT_LABELS = {
  [ALERT_TYPES.OVERSPEED]: 'Overspeed',
  [ALERT_TYPES.ENGINE_ON]: 'Ignition ON',
  [ALERT_TYPES.ENGINE_OFF]: 'Ignition OFF',
  [ALERT_TYPES.GEOFENCE_ENTER]: 'Geofence Enter',
  [ALERT_TYPES.GEOFENCE_EXIT]: 'Geofence Exit',
  [ALERT_TYPES.BATTERY_DISCONNECTED]: 'Battery Disconnected',
  [ALERT_TYPES.DEVICE_EXPIRY]: 'Device Expiry',
  [ALERT_TYPES.CALL_REQUIRED]: 'Call Required',  // ✅ added
};

export const ALERT_ICONS = {
  [ALERT_TYPES.OVERSPEED]: '🚨',
  [ALERT_TYPES.ENGINE_ON]: '🔑',
  [ALERT_TYPES.ENGINE_OFF]: '⛔',
  [ALERT_TYPES.GEOFENCE_ENTER]: '📍',
  [ALERT_TYPES.GEOFENCE_EXIT]: '📌',
  [ALERT_TYPES.BATTERY_DISCONNECTED]: '🔋',
  [ALERT_TYPES.DEVICE_EXPIRY]: '⏰',
  [ALERT_TYPES.CALL_REQUIRED]: '📞',
};

export const CRITICAL_ALERT_TYPES = [
  ALERT_TYPES.BATTERY_DISCONNECTED,
  ALERT_TYPES.GEOFENCE_EXIT,
  ALERT_TYPES.DEVICE_EXPIRY,
  ALERT_TYPES.CALL_REQUIRED,
];

export const isCriticalAlert = (type) => CRITICAL_ALERT_TYPES.includes(type);