export const PERMISSIONS = {
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_DEVICES: "MANAGE_DEVICES",
  MANAGE_GEOFENCES: "MANAGE_GEOFENCES",
  MANAGE_ALERTS: "MANAGE_ALERTS",
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  SEND_COMMANDS: "SEND_COMMANDS",
  RENEW_DEVICES: "RENEW_DEVICES",
  MANAGE_TRACKER_MODELS: "MANAGE_TRACKER_MODELS",
};